import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import MainPage from "../components/layouts/main.layout"
import { withRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

 function Home() {
  return (
    <>
      <Head>
        <title>School website temp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}


const PageWithRouter = withRouter(Home);
PageWithRouter.getLayout = function getLayout(page) {
  return <MainPage>{page}</MainPage>;
};
export default PageWithRouter;
